version: "3"

networks:
  home-server:
    external: true

services:
  hs-db:
    container_name: hs-db
    image: mysql:8
    restart: always
    networks:
    - home-server
    volumes:
    - ./mysql:/var/lib/mysql
