# Please make cloud directory first if this fails

version: '3.7'

networks:
  home-server:
    external: true

services:
  hs-cloud:
    container_name: hs-cloud
    image: pydio/cells:4.2
    restart: always
    environment:
      CELLS_SITE_NO_TLS: 1
      CELLS_SITE_EXTERNAL: https://your.domain.name.for.cloud
      CELLS_INSTALL_YAML: /pydio/config/install.yaml
    ports: 
    - your.port.number.0007:8080
    networks:
    - home-server
    volumes:
    - ./install-conf.yaml:/pydio/config/install.yaml:ro
    - /mnt/hdd/cloud/cells:/var/cells

  hs-cloud-db:
    container_name: hs-cloud-db
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your-PW
      MYSQL_DATABASE: cells
      MYSQL_USER: pydio
      MYSQL_PASSWORD: your-PW
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
    networks:
    - home-server
    volumes:
    - /mnt/hdd/cloud/mysql:/var/lib/mysql

