version: "3"

networks:
  home-server:
    external: true

services:
  hs-proxy:
    container_name: hs-proxy
    image: envoyproxy/envoy:v1.27.0
    restart: always
    ports:
    - your.port.number.0003:your.port.number.0001
    - 443:your.port.number.0002
    networks:
    - home-server
    volumes:
    - ./volume/envoy:/etc/envoy
    command:
    - envoy
    - -c /etc/envoy/envoy.yaml
    - -l info

