version: "3"

networks:
  home-server:
    external: true

services:
  hs-git:
    container_name: hs-git
    image: gitlab/gitlab-ce:16.3.4-ce.0
    restart: always
    hostname: your.IP.addr
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://your.domain.name.for.git/'
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        letsencrypt['enable'] = false
        gitlab_rails['gitlab_shell_ssh_port'] = your.port.number.0004
        prometheus_monitoring['enable'] = false
    ports:
    - your.port.number.0005:80
    - your.port.number.0006:443
    - your.port.number.0004:22
    networks:
    - home-server
    volumes:
    - ./volume/config:/etc/gitlab
    - ./volume/logs:/var/log/gitlab
    - ./volume/data:/var/opt/gitlab
    deploy:
      resources:
        limits:
          memory: 12G
        reservations:
          memory: 4G
    shm_size: 256m

