version: "3"

networks:
  home-server:
    external: true

services:
  hs-git:
    container_name: hs-git
    image: gitea/gitea:1.21.5
    restart: always
    environment:
    - USER_UID=1000
    - USER_GID=1000
    - GITEA__database__DB_TYPE=mysql
    - GITEA__database__HOST=hs-db:3306
    - GITEA__database__NAME=gitea
    - GITEA__database__USER=<ID>
    - GITEA__database__PASSWD=<PW>
    networks:
    - home-server
    volumes:
    - ./gitea:/data
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    ports:
    - <PORT>:3000
    - <PORT>:22
